classes:
  nodejs:
  adblockplus::legacy::webserver:

# adblockplus::mercurial::extensions:
#   hggit:
#     package:
#       ensure: latest
#       name: hg-git
#       provider: pip

sitescripts::configfragments:
  formmail_template:
    content: |
      [multiplexer]
      sitescripts.subscriptions.web.fallback =
      [subscriptions]
      repository=/home/www/subscriptionlist

