classes:
  nodejs:
  adblockplus::legacy::webserver:

nodejs::packages:
  jsdoc:

sitescripts::configfragments:
  formmail_template:
    content: |
      [multiplexer]
      sitescripts.subscriptions.web.fallback =
      [subscriptions]
      repository=/home/www/subscriptionlist

