classes:
  nodejs:
  adblockplus::legacy::webserver:

adblockplus::mercurial::extensions:
  hggit:
    package:
      ensure: 0.8.9
      name: hg-git
      provider: pip
      install_options:
        - https://pypi.python.org/pypi/hg-git

sitescripts::configfragments:
  formmail_template:
    content: |
      [multiplexer]
      sitescripts.subscriptions.web.fallback =
      [subscriptions]
      repository=/home/www/subscriptionlist

