classes:
  nodejs:
  adblockplus::legacy::webserver:

web::server::remote: git://github.com/adblockplus/web.adblockplus.org.git

sitescripts::configfragments:
  formmail_template:
    content: |
      [multiplexer]
      sitescripts.subscriptions.web.fallback =
      [subscriptions]
      repository=/home/www/subscriptionlist

