classes:
  adblockplus:
  adblockplus::sudo:
  nagios::client:
    server_address: monitoring.adblockplus.org

adblockplus::log::uplink:
  log@log1.adblockplus.org

adblockplus::packages:
  - "debian-goodies"
  - "mercurial"
  - "vim"

adblockplus::users:
  test:
    authorized_keys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDLrPR2CZLSs6tKSEUBeaahzcKhWwQAN9Hwcrn5HpS0FTz3VFbyJXNP5KZYci3zF6/CHNSM1iOkV6t/6U8g16+PWOo5pMNg7jWqoZD6ukT+cX6ZuNm8CtIx7EzwFxGB8INrKAonmpG9FRWHMppi4nJG5SrQv2rgoUDt+Dbu2oPMh/EGUS2wQ7VUwA1/qAeRsAdptrGB6wr/+1fGTdrZy11AG+sLnrO+VXIShOFCuv9czbj9nw5Bi6jwnWrzvfQx1BfwVwYtdfGSprB6p+8aL7u3SCF+aJAGGRoYjqec4+EM5xRJ3grmoFtkngEiJIaLWRPkgD8uggY2spmff1Ypl24v test@example.com"
    groups:
      - adm
      - staff
      - sudo
      - users
    password_hash: "$6$k.fe9F4U$OIav.SJZuujVfXk4HTKS.i94ZuQtoJNCH6KH1ePar57yc3y51G0PbGPXT6zO5v.q3h5TM87MDx0QEX4TTENq.0"

adblockplus::hosts:
  filter1:
    ips: [10.8.0.120]
    role: filterserver
    public_key: &vagrant_box
      AAAAB3NzaC1yc2EAAAADAQABAAABAQDkXTOj2JwvwlDaHbaMrDuosuRuU5ZuKe1EHNJa67ZxkB1a6Y1ObDxfYiYnvI5i9sQyUmmc5TrGAGGJs1BrriMaPayBaTSf3ymU2Rqxj3GZXuiioCxGV8I2R/aOhwvpbnVqZH5O99IuAZbrag5J/WhDWgWuk3gFrZxEwQmZW144tJH//I3b0oMAr3/arBViVeU52dHhKX9xdStTzFpWKUav/NoKKrgB91QKwPx8U6ymuDoCQU7qyTBnAX1sYuSwEMJzVRqtmKLybR4Xp5A94EMbJsgVbq4LrUrMo00FdLV0EGMmA2Kmd/9D+CuZXoD6/mWkzmaVfiUMKhrorM05voFp
    groups: [filter-servers]
  server4:
    ips: [10.8.0.99]
    role: monitoringserver
    public_key: *vagrant_box
    groups: [http-servers]
  codereview1:
    ips: [10.8.0.132]
    role: codereviewserver
    public_key: *vagrant_box
    groups: [http-servers]
  download1:
    ips: [10.8.0.126]
    role: downloadserver
    public_key: *vagrant_box
    groups: [http-servers]
  filtermaster1:
    ips: [10.8.0.127]
    role: filtermasterserver
    public_key: *vagrant_box
  server10:
    ips: [10.8.0.105]
    role: intraforumserver
    public_key: *vagrant_box
    groups: [http-servers]
  issues1:
    ips: [10.8.0.131]
    public_key: *vagrant_box
    groups: [http-servers]
  stats1:
    ips: [10.8.0.130]
    role: statsmaster
    public_key: *vagrant_box
    groups: [http-servers]
  update1:
    ips: [10.8.0.128]
    role: updateserver
    public_key: *vagrant_box
    groups: [http-servers]
  web1:
    ips: [10.8.0.129]
    role: web/eyeo
    public_key: *vagrant_box
    groups: [http-servers]
  web2:
    ips: [10.8.0.145]
    public_key: *vagrant_box
    groups: [http-servers]
  web3:
    ips: [10.8.0.146]
    role: web/testpages
    public_key: *vagrant_box
    groups: [http-servers]
  web-sh-abp-org-1:
    ips: [10.8.0.147]
    role: web/share
    public_key: *vagrant_box
    groups: [http-servers]
  web-yt-abp-me-1:
    ips: [10.8.0.148]
    role: web/youtube
    public_key: *vagrant_box
    groups: [http-servers]
  web-fb-abp-me-1:
    ips: [10.8.0.149]
    role: web/facebook
    public_key: *vagrant_box
    groups: [http-servers]
  web-aa-com-1:
    ips: [10.8.0.150]
    role: web/acceptableads
    public_key: *vagrant_box
    groups: [http-servers]
  hg1:
    ips: [10.8.0.152]
    role: hgwebserver
    public_key: *vagrant_box
    groups: [http-servers]
  build1:
    ips: [10.8.0.153]
    role: buildmasterserver
    public_key: *vagrant_box
    groups: [http-servers]
  web-abb-org-1:
    ips: [10.8.0.154]
    role: web/adblockbrowser
    public_key: *vagrant_box
    groups: [http-servers]
  web-subscribe-abp-org-1:
    ips: [10.8.0.155]
    role: web/subscribe
    public_key: *vagrant_box
    groups: [http-servers]
  web-easylist-abp-org-1:
    ips: [10.8.0.156]
    role: web/easylist
    public_key: *vagrant_box
    groups: [http-servers]
  log1:
    ips: [10.8.0.210]
    role: logserver
    public_key: *vagrant_box
  logprocessor1:
    ips: [10.8.0.211]
    role: logprocessor
    public_key: *vagrant_box
  telemetry1:
    ips: [10.8.0.220]
    role: telemetryserver
    public_key: *vagrant_box
    groups: [http-servers]

cron::environment:
  - MAILTO=root,vagrant

